"""empty message

Revision ID: 0122e1470673
Revises: e3672be8198b
Create Date: 2019-07-02 19:50:29.773320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0122e1470673'
down_revision = 'e3672be8198b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('key_word', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'key_word')
    # ### end Alembic commands ###
