"""empty message

Revision ID: 4bc394e47b0b
Revises: 792e2bc0966e
Create Date: 2019-07-02 21:14:54.981752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc394e47b0b'
down_revision = '792e2bc0966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
