"""empty message

Revision ID: 607d8ffc8da8
Revises: 0122e1470673
Create Date: 2019-07-02 19:52:06.330464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607d8ffc8da8'
down_revision = '0122e1470673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'desc')
    # ### end Alembic commands ###
