"""empty message

Revision ID: 792e2bc0966e
Revises: e0ed5038c331
Create Date: 2019-07-02 20:45:33.370149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '792e2bc0966e'
down_revision = 'e0ed5038c331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('atime', sa.DateTime(), nullable=True))
    op.drop_column('article', 'atimed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('atimed', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'atime')
    # ### end Alembic commands ###
