"""empty message

Revision ID: e0ed5038c331
Revises: 607d8ffc8da8
Create Date: 2019-07-02 20:45:24.479295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0ed5038c331'
down_revision = '607d8ffc8da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('atimed', sa.DateTime(), nullable=True))
    op.drop_column('article', 'atime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('atime', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'atimed')
    # ### end Alembic commands ###
