"""empty message

Revision ID: e3672be8198b
Revises: e3c1bb86ea09
Create Date: 2019-07-02 19:45:20.457072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3672be8198b'
down_revision = 'e3c1bb86ea09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('atime', sa.DateTime(), nullable=True))
    op.drop_column('article', 'atimed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('atimed', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'atime')
    # ### end Alembic commands ###
